// words.js — 体检（audit）用词频分段抽样库。
// 分段口径对齐 en20k-audit：1-3k 高中核心 / 3-6k 四六级 / 6-10k 考研雅思 / 10-15k 原版小说 / 15-20k 文学口语。
// 复测从同库洗牌重抽（结构相同、词序不同，保证跨月可比）。
export const BANDS = [
  {
    key: '1-3k', label: '1–3k · 高中核心', size: 3000, sample: 15,
    words: [
      ['achieve', '实现，达到'], ['admire', '钦佩，欣赏'], ['ancient', '古老的'],
      ['apologize', '道歉'], ['arrange', '安排'], ['attempt', '尝试'],
      ['avoid', '避免'], ['benefit', '好处；受益'], ['brief', '简短的'],
      ['challenge', '挑战'], ['complain', '抱怨'], ['concentrate', '专注'],
      ['confirm', '确认'], ['consider', '考虑'], ['contribute', '贡献'],
      ['curious', '好奇的'], ['disappoint', '使失望'], ['encourage', '鼓励'],
      ['familiar', '熟悉的'], ['generous', '慷慨的'], ['handle', '处理'],
      ['imagine', '想象'], ['independent', '独立的'], ['influence', '影响'],
      ['mention', '提到'], ['nervous', '紧张的'], ['ordinary', '普通的'],
      ['patient', '耐心的'], ['polite', '礼貌的'], ['prefer', '更喜欢'],
      ['prevent', '阻止'], ['realize', '意识到'], ['refuse', '拒绝'],
      ['regret', '后悔'], ['remind', '提醒'], ['require', '需要'],
      ['satisfy', '使满意'], ['serious', '严肃的'], ['share', '分享'],
      ['similar', '相似的'], ['succeed', '成功'], ['suggest', '建议'],
      ['threaten', '威胁'], ['trust', '信任'],
    ],
  },
  {
    key: '3-6k', label: '3–6k · 四六级', size: 3000, sample: 20,
    words: [
      ['abandon', '放弃'], ['absorb', '吸收'], ['accelerate', '加速'],
      ['accompany', '陪伴'], ['accomplish', '完成'], ['accumulate', '积累'],
      ['accurate', '准确的'], ['accuse', '指控'], ['acquire', '获得'],
      ['adapt', '适应'], ['adequate', '足够的'], ['adjust', '调整'],
      ['adopt', '采纳；收养'], ['aggressive', '好斗的；进取的'], ['anticipate', '预期'],
      ['apparent', '明显的'], ['appeal', '呼吁；吸引力'], ['appropriate', '恰当的'],
      ['approximate', '大约的'], ['arbitrary', '任意的'], ['assess', '评估'],
      ['assume', '假定'], ['attribute', '归因于'], ['available', '可获得的'],
      ['campaign', '运动；活动'], ['candidate', '候选人'], ['capacity', '容量；能力'],
      ['category', '类别'], ['circumstance', '情况，环境'], ['collaborate', '合作'],
      ['compensate', '补偿'], ['competent', '胜任的'], ['comprehensive', '全面的'],
      ['conduct', '进行；指挥'], ['conflict', '冲突'], ['conscious', '有意识的'],
      ['consent', '同意'], ['considerable', '相当大的'], ['consistent', '一致的'],
      ['consult', '咨询'], ['consume', '消耗'], ['convey', '传达'],
      ['crucial', '关键的'], ['decline', '下降；婉拒'], ['demonstrate', '证明'],
      ['distinguish', '区分'], ['distribute', '分发'], ['diverse', '多样的'],
      ['efficient', '高效的'], ['emerge', '出现'], ['emphasize', '强调'],
      ['enormous', '巨大的'], ['evaluate', '评估'], ['evident', '明显的'],
      ['exceed', '超过'], ['expand', '扩展'], ['facilitate', '促进'],
      ['flexible', '灵活的'], ['fundamental', '根本的'], ['guarantee', '保证'],
      ['identify', '识别'], ['indicate', '表明'], ['inevitable', '不可避免的'],
      ['initiate', '发起'], ['legitimate', '合法的'], ['modify', '修改'],
      ['notion', '观念'], ['obstacle', '障碍'], ['perspective', '视角'],
      ['plausible', '貌似合理的'], ['precise', '精确的'], ['priority', '优先'],
      ['profound', '深刻的'], ['reluctant', '不情愿的'], ['resolve', '解决；决心'],
      ['substantial', '大量的'], ['sufficient', '足够的'], ['sustain', '维持'],
      ['undermine', '暗中破坏'], ['versatile', '多才多艺的'],
    ],
  },
  {
    key: '6-10k', label: '6–10k · 考研/雅思', size: 4000, sample: 20,
    words: [
      ['alleviate', '缓解'], ['ambiguous', '模棱两可的'], ['ample', '充足的'],
      ['analogy', '类比'], ['articulate', '表达清晰的'], ['assert', '断言'],
      ['astute', '精明的'], ['authentic', '真实的'], ['avid', '热衷的'],
      ['baffle', '使困惑'], ['bolster', '支撑，提振'], ['candid', '坦率的'],
      ['catalyst', '催化剂'], ['coherent', '连贯的'], ['coincide', '巧合；一致'],
      ['compelling', '令人信服的'], ['conducive', '有助于的'], ['conspicuous', '显眼的'],
      ['constrain', '限制'], ['contemplate', '沉思'], ['contradict', '反驳'],
      ['cumbersome', '笨重的'], ['daunting', '令人生畏的'], ['deduce', '推断'],
      ['deliberate', '蓄意的；深思'], ['detrimental', '有害的'], ['deviate', '偏离'],
      ['diligent', '勤奋的'], ['discern', '辨别'], ['discreet', '谨慎的'],
      ['discrepancy', '差异'], ['elusive', '难以捉摸的'], ['eminent', '杰出的'],
      ['empirical', '实证的'], ['endeavor', '努力'], ['erode', '侵蚀'],
      ['exemplary', '堪称典范的'], ['exhaustive', '详尽无遗的'], ['feasible', '可行的'],
      ['fluctuate', '波动'], ['formulate', '制定；阐述'], ['hinder', '阻碍'],
      ['hypothesis', '假说'], ['imperative', '势在必行的'], ['implicit', '含蓄的'],
      ['incentive', '激励'], ['inhibit', '抑制'], ['intricate', '错综复杂的'],
      ['intuition', '直觉'], ['intrigue', '激起兴趣；密谋'],
    ],
  },
  {
    key: '10-15k', label: '10–15k · 原版小说高频', size: 5000, sample: 15,
    words: [
      ['abhor', '憎恶'], ['aloof', '冷漠疏远的'], ['amiable', '和蔼可亲的'],
      ['antiquated', '过时的'], ['apathy', '冷漠'], ['ardent', '热烈的'],
      ['assuage', '平息，缓和'], ['austere', '严苛简朴的'], ['aversion', '厌恶'],
      ['belligerent', '好斗的'], ['bequeath', '遗赠'], ['brazen', '厚颜无耻的'],
      ['capricious', '反复无常的'], ['caustic', '刻薄的'], ['composure', '镇定'],
      ['condone', '纵容'], ['contrite', '悔悟的'], ['copious', '大量的'],
      ['cordial', '热诚的'], ['credulous', '轻信的'], ['decorum', '礼仪'],
      ['demure', '端庄害羞的'], ['despondent', '沮丧的'], ['diffident', '缺乏自信的'],
      ['dilapidated', '破旧的'], ['disheveled', '凌乱的'], ['ebullient', '热情洋溢的'],
      ['eclectic', '兼收并蓄的'], ['effusive', '溢于言表的'], ['elucidate', '阐明'],
      ['enervate', '使虚弱'], ['equanimity', '平静，泰然'], ['extol', '赞颂'],
      ['facetious', '玩笑不当的'], ['fastidious', '挑剔的'], ['flippant', '轻率的'],
      ['forlorn', '孤苦凄凉的'], ['frugal', '节俭的'], ['garrulous', '唠叨的'],
      ['gregarious', '爱交际的'], ['hackneyed', '陈腐的'], ['idyllic', '田园牧歌式的'],
      ['impervious', '无动于衷的'], ['inadvertent', '无意的'], ['indignant', '愤慨的'],
      ['innocuous', '无害的'], ['insipid', '乏味的'], ['jubilant', '欢欣鼓舞的'],
      ['laconic', '寡言简洁的'], ['languid', '倦怠的'], ['magnanimous', '宽宏大量的'],
      ['melancholy', '忧郁的'], ['meticulous', '一丝不苟的'], ['nefarious', '邪恶的'],
      ['obsequious', '谄媚的'], ['ostentatious', '炫耀的'], ['pedantic', '迂腐的'],
      ['pensive', '沉思的'], ['placate', '抚慰'], ['prescient', '有先见之明的'],
      ['prodigal', '挥霍的'], ['propensity', '倾向'], ['quaint', '古雅的'],
      ['quell', '平息'], ['rancor', '怨恨'], ['reciprocate', '回报'],
      ['reticent', '沉默寡言的'], ['rue', '后悔'], ['sagacious', '睿智的'],
      ['sardonic', '讥讽的'], ['solace', '安慰'], ['somber', '阴沉的'],
      ['spartan', '简朴的'], ['superfluous', '多余的'], ['tenacious', '坚韧的'],
      ['truculent', '粗暴好斗的'], ['venerate', '尊敬'], ['vex', '使恼火'],
      ['vitriolic', '尖酸刻薄的'], ['whimsical', '异想天开的'], ['wistful', '怅惘的'],
    ],
  },
  {
    key: '15-20k', label: '15–20k · 文学/地道口语', size: 5000, sample: 10,
    words: [
      ['abstruse', '深奥的'], ['acerbic', '尖刻的'], ['alacrity', '欣然乐意'],
      ['apocryphal', '真伪可疑的'], ['asinine', '愚蠢的'], ['bedlam', '喧闹混乱'],
      ['blithe', '无忧无虑的；轻率的'], ['byzantine', '错综复杂的'], ['cadge', '讨要'],
      ['chary', '谨慎的'], ['churlish', '粗暴无礼的'], ['curmudgeon', '脾气坏的人'],
      ['dastardly', '卑鄙怯懦的'], ['effete', '衰弱的；娇气的'], ['encomium', '赞颂'],
      ['execrable', '糟糕透顶的'], ['feckless', '无用而不负责的'], ['gainsay', '否认'],
      ['harangue', '长篇抨击'], ['impecunious', '身无分文的'], ['inchoate', '初步未成形的'],
      ['iniquity', '邪恶'], ['insouciant', '漫不经心的'], ['internecine', '两败俱伤的'],
      ['lachrymose', '爱哭的'], ['maudlin', '多愁善感的'], ['mendacious', '撒谎的'],
      ['moribund', '垂死的'], ['obdurate', '顽固的'], ['pandemonium', '大混乱'],
      ['perfidious', '背信弃义的'], ['pusillanimous', '胆怯的'], ['recalcitrant', '顽抗的'],
      ['remiss', '疏忽的'], ['risible', '可笑的'], ['salubrious', '有益健康的'],
      ['scurrilous', '辱骂的'], ['sententious', '说教的'], ['splenetic', '脾气坏的'],
      ['trope', '套路，惯用手法'], ['vapid', '乏味的'], ['vituperative', '责骂的'],
      ['wan', '苍白无力的'], ['zealot', '狂热者'],
    ],
  },
];
